<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.epam.dao.impl.TstNewsDAOAdd" tests="4" time="0.020" ignored="0" failures="0" timestamp="05 фев 2017 22:49:09 GMT" skipped="0" hostname="DESKTOP-0D9IMT3" errors="1">
  <testcase name="tstAddNews" time="0.017" classname="com.epam.dao.impl.TstNewsDAOAdd"/>
  <testcase name="tstAddNews" time="0.000" classname="com.epam.dao.impl.TstNewsDAOAdd">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: tstAddNews([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=com.epam.bean.News, declaredAnnotations=[]}])
Arguments: [(com.epam.bean.News)title = Oscar_nominees, category = Film, content = text_of_news
]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: tstAddNews([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=com.epam.bean.News, declaredAnnotations=[]}])
Arguments: [(com.epam.bean.News)title = Oscar_nominees, category = Film, content = text_of_news
]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1278)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1171)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- tstAddNews -->
  <testcase name="tstAddNews" time="0.003" classname="com.epam.dao.impl.TstNewsDAOAdd"/>
  <testcase name="tstAddNews" time="0.000" classname="com.epam.dao.impl.TstNewsDAOAdd"/>
</testsuite> <!-- com.epam.dao.impl.TstNewsDAOAdd -->
